// apps/ticketapp/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Ticket } from '@mycompany/api-types';

@Component({
  selector: 'mycompany-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  tickets =  this.http.get<Ticket[]>('/api/tickets');

  constructor(private readonly http: HttpClient) {
  }
}

<mycompany-header title="Tickets"></mycompany-header>

<ul>
  <li *ngFor="let t of tickets|async">
    {{ t.title }}
  </li>
</ul>

// apps/admin/src/app/app.tsx
import * as React from 'react';
import { Component } from 'react';
import axios from 'axios';

import './app.css';
import { Ticket } from '@mycompany/api-types';

export class App extends Component<{}, { tickets: Ticket[] }> {
  state = {
    tickets: []
  };

  async componentWillMount() {
    const { data: tickets } = await axios('/api/tickets');
    this.setState({ tickets });
  }

  render() {
    return (
      <>
        <mycompany-header title={'Tickets admin!'} />
        <ul>
          {this.state.tickets.map(t => (
            <li key={t.title}>
              {t.title} | {t.adminComment}
            </li>
          ))}
        </ul>
      </>
    );
  }
}
